---
title: "Problem 5"
output: html_document
---



```{r}
library(ggplot2)
data(diamonds)
names(diamonds)
range(diamonds$price)
```

### Price Histograms with Facet and Color
```{r}
subset(diamonds, color == 'D')
ggplot(aes(x=price, fill=cut), data=diamonds) + geom_histogram(binwidth=.13) + scale_x_log10() + facet_wrap(~color, ncol=3) + scale_fill_brewer(type = 'qual')
```

### Price vs. Table Colored by Cut
```{r}
range(diamonds$table)
ggplot(aes(x=table, y=price), data=diamonds) + geom_point(aes(color=cut)) + scale_fill_brewer(type = 'qual') + scale_x_continuous(limits=c(50, 80), breaks=seq(50, 80, 2))
```

### Price vs. Volume and Diamond Clarity
```{r}
diamonds <- 
  transform(diamonds, volume=x * y * z)
summary(diamonds)
head(diamonds)
range(diamonds$clarity)
ggplot(aes(x=volume, y=price), data=subset(diamonds, !is.na(volume))) + geom_point(aes(color=clarity)) + scale_y_log10() + scale_color_brewer(type = 'div') + xlim(0, quantile(diamonds$volume, 0.99))
```

### Proportion of Friendships Initiated

```{r}
setwd('/Volumes/MacHD/Projects/P3-Data-Analysis-with-R')
pf <- read.csv('pseudo_facebook.tsv', sep='\t')
names(pf)
pf$prop_initiated <- pf$friendships_initiated/pf$friend_count
```

### prop_initiated vs. tenure

```{r}
pf$year_joined <- floor(2014 - pf$tenure / 365)
pf$year_joined.bucket<-cut(pf$year_joined, c(2004,2009,2011,2012, 2014))
ggplot(data = pf, aes(x = tenure, y = prop_initiated)) + geom_line(stat = 'summary', fun.y = median, aes(color = year_joined.bucket))
```

### Smoothing prop_initiated vs. tenure

```{r}
ggplot(data = pf, aes(x = tenure, y = prop_initiated)) + geom_line(stat = 'summary', fun.y = median, aes(color = year_joined.bucket)) + geom_smooth()
```

### Largest Group Mean prop_initiated
```{r}
with(subset(pf,year_joined>2012), summary(prop_initiated))
```

### Price/Carat Binned, Faceted, & Colored
```{r}
ggplot(data=diamonds, aes(x=cut,y=price/carat)) + geom_jitter(aes(color=color)) + facet_wrap(~clarity, ncol=3) + scale_color_brewer(type = 'div')
```
